name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
- uses: actions/setup-node@v4
  with: { node-version: '20', cache: 'npm' }
- run: npm ci

- name: Cypress - angular-lab
  uses: cypress-io/github-action@v6
  with:
    build: npx nx build angular-lab
    start: npx nx serve angular-lab --port 4200
    wait-on: 'http://localhost:4200'
    command: npx nx e2e angular-lab-e2e
- name: Cypress - clinic
  uses: cypress-io/github-action@v6
  with:
    build: npx nx build clinic
    start: npx nx serve clinic --port 4300
    wait-on: 'http://localhost:4300'
    command: npx nx e2e clinic-e2e
